name = "digital-card-platform"
compatibility_date = "2024-01-01"

[build]
command = "cd client && npm install && npm run build"
cwd = "client"
watch_dir = "client/src"

pages_build_output_dir = "client/dist"
